---
- name: Include disable_default_motd.yml if motd_disable_default_motd is True
  ansible.builtin.include_tasks: disable_default_motd.yml
  when: motd_disable_default_motd|bool

- name: Include configure_motd.yml
  ansible.builtin.include_tasks: configure_motd.yml
...
