---
dependency:
  name: shell
  command: python3 -m pip install pytest-testinfra

driver:
  name: docker

platforms:
  # On "${name:-${image:-debian}", the last brace does not miss, it works like that...
  # The env var should be used when the image variable refers to a full registry path like registry.access.redhat.com/ubi8/ubi
  - name: claranet_motd_${name:-${image:-debian}-${tag:-latest}-${scenario:-default}
    image: ${image:-debian}:${tag:-latest}
    privileged: true
    tty: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    stop_signal: "SIGRTMIN+3"
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  options:
    v: true

verifier:
  name: testinfra
  options:
    verbose: true
    s: true

lint: |
  set -e
  yamllint .
  ansible-lint
