---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: claranet_motd_${image:-debian}-${tag:-latest}
    image: ${image:-debian}:${tag:-latest}
    privileged: true
    tty: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    stop_signal: "SIGRTMIN+3"
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  options:
    v: true

verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    verbose: true
    s: true

lint: |
  set -e
  yamllint .
  ansible-lint
